import {ref} from 'vue';

export type Language = 'pt-BR' | 'en' | 'es';

const LANGUAGE_STORAGE_KEY = 'workhub-language';

const messages = {
    'pt-BR': {
        'language.label': 'Idioma',
        'language.pt-BR': 'Português - BR',
        'language.en': 'Inglês',
        'language.es': 'Espanhol',
        'theme.light': 'Ativar modo claro',
        'theme.dark': 'Ativar modo escuro',
        'auth.bannerAlt': 'Workhub, um hub completo para organizar, colaborar e entregar mais.',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'voce@empresa.com',
        'auth.password': 'Senha',
        'auth.passwordPlaceholder': 'Sua senha',
        'auth.login.eyebrow': 'Login',
        'auth.login.title': 'Acesse sua conta',
        'auth.login.description': 'Entre para continuar acompanhando suas tarefas, projetos e entregas.',
        'auth.login.submit': 'Entrar',
        'auth.login.noAccount': 'Ainda não tem uma conta?',
        'auth.login.createAccount': 'Criar conta',
        'auth.register.eyebrow': 'Cadastro',
        'auth.register.title': 'Crie sua conta',
        'auth.register.description': 'Depois do registro, você já entra autenticado no Workhub.',
        'auth.register.firstName': 'Nome',
        'auth.register.firstNamePlaceholder': 'Seu nome',
        'auth.register.lastName': 'Sobrenome',
        'auth.register.lastNamePlaceholder': 'Seu sobrenome',
        'auth.register.username': 'Username',
        'auth.register.passwordPlaceholder': 'Mínimo de 8 caracteres',
        'auth.register.submit': 'Criar conta',
        'auth.register.hasAccount': 'Já tem uma conta?',
        'auth.register.signIn': 'Entrar',
        'validation.email': 'Informe um email válido.',
        'validation.passwordRequired': 'Informe sua senha.',
        'validation.passwordMin': 'A senha deve ter pelo menos 8 caracteres.',
        'validation.usernameMin': 'O username deve ter pelo menos 2 caracteres.',
        'validation.usernameMax': 'O username deve ter no máximo 30 caracteres.',
        'validation.lastNameMin': 'O sobrenome deve ter pelo menos 2 caracteres.',
        'validation.lastNameMax': 'O sobrenome deve ter no máximo 30 caracteres.',
        'validation.firstNameMin': 'O nome deve ter pelo menos 2 caracteres.',
        'validation.firstNameMax': 'O nome deve ter no máximo 20 caracteres.',
        'toast.success': 'Operação concluída',
        'toast.error': 'Não foi possível concluir',
        'auth.register.success': 'Usuário registrado com sucesso!',
        'auth.register.error': 'Ocorreu um erro ao realizar o registro, tente novamente mais tarde!',
        'auth.login.success': 'Login realizado com sucesso!',
        'auth.login.error': 'Email ou senha inválidos.',
        'demands.nav': 'Demandas',
        'demands.mainNav': 'Navegação principal',
        'demands.user': 'Usuário',
        'demands.search': 'Pesquisar demandas',
        'demands.searchPlaceholder': 'Buscar por título',
        'demands.clearSearch': 'Limpar pesquisa',
        'demands.logout': 'Sair',
        'demands.personalPanel': 'Painel pessoal',
        'demands.heading': 'Demandas em',
        'demands.headingEmphasis': 'movimento.',
        'demands.intro': 'Uma visão direta do trabalho que precisa avançar.',
        'demands.register': 'Registrar demanda',
        'demands.currentSlice': 'Recorte atual',
        'demands.items': 'Itens',
        'demands.ongoing': 'Em curso',
        'demands.urgent': 'Urgentes',
        'demands.overdue': 'Atrasadas',
        'demands.closed': 'Fechadas',
        'demands.queue': 'Fila de trabalho',
        'demands.onTable': 'O que está na mesa',
        'demands.boardKicker': 'Visão por status',
        'demands.boardTitle': 'Board de demandas',
        'demands.addToColumn': 'Adicionar em',
        'demands.emptyColumn': 'Nenhuma demanda neste status.',
        'demands.moveSuccess': 'Status da demanda atualizado.',
        'demands.moveError': 'Não foi possível mover a demanda.',
        'demands.filterByStatus': 'Filtrar por status',
        'demands.allStatus': 'Todos os status',
        'demands.filterByPriority': 'Filtrar por prioridade',
        'demands.allPriorities': 'Todas as prioridades',
        'demands.refresh': 'Atualizar demandas',
        'demands.loading': 'Atualizando a fila...',
        'demands.emptyTitle': 'Fila livre.',
        'demands.emptyDescription': 'Registre a próxima demanda para colocar o trabalho em movimento.',
        'demands.noDeadline': 'Sem prazo definido',
        'demands.notFinalized': 'Não finalizada',
        'demands.edit': 'Editar demanda',
        'demands.delete': 'Excluir demanda',
        'demands.viewDetails': 'Ver detalhes da demanda',
        'demands.detailsKicker': 'Detalhes da demanda',
        'demands.createdAt': 'Criada em',
        'demands.updatedAt': 'Última atualização',
        'demands.neverUpdated': 'Ainda não atualizada',
        'demands.page': 'Folha',
        'demands.of': 'de',
        'demands.previousPage': 'Página anterior',
        'demands.nextPage': 'Próxima página',
        'demands.editKicker': 'Ajuste de rota',
        'demands.newKicker': 'Entrada rápida',
        'demands.new': 'Nova demanda',
        'demands.editDescription': 'Atualize o registro conforme o trabalho avança.',
        'demands.newDescription': 'Capture agora. Refine enquanto executa.',
        'demands.backToBoard': 'Voltar ao board',
        'demands.createHeading': 'Transforme uma necessidade em trabalho claro.',
        'demands.createDescription': 'Registre o contexto essencial para que a demanda possa avançar sem depender de informações dispersas.',
        'demands.createHintContext': 'Explique o resultado esperado',
        'demands.createHintPriority': 'Defina prioridade e status inicial',
        'demands.createHintDeadline': 'Informe um prazo quando necessário',
        'demands.cancelCreate': 'Cancelar',
        'demands.title': 'Título',
        'demands.titlePlaceholder': 'Ex.: Revisar endpoint de clientes',
        'demands.description': 'Descrição',
        'demands.descriptionPlaceholder': 'Descreva o que precisa ser realizado',
        'demands.reviewNote': 'Anotação para review',
        'demands.optional': 'opcional',
        'demands.reviewNotePlaceholder': 'Registre contexto, decisões ou o resultado esperado para consultar no review',
        'demands.observations': 'Observações',
        'demands.newObservations': 'Novas observações',
        'demands.existingObservations': 'Observações existentes',
        'demands.observationPlaceholder': 'Escreva uma observação sobre esta demanda',
        'demands.addObservation': 'Adicionar observação',
        'demands.addAnotherObservation': 'Adicionar outra observação',
        'demands.saveObservations': 'Salvar observações',
        'demands.removeObservation': 'Remover observação',
        'demands.noObservations': 'Nenhuma observação registrada.',
        'demands.deadline': 'Prazo',
        'demands.finalizedAt': 'Finalizada em',
        'demands.status': 'Status',
        'demands.priority': 'Prioridade',
        'demands.save': 'Salvar alterações',
        'demands.cancelEdit': 'Cancelar edição',
        'demands.footerTagline': 'Seu registro diário de entregas.',
        'demands.footerText': 'Organize o presente. Documente o que avançou.',
        'demands.backToTop': 'Voltar ao topo',
        'demands.deleteKicker': 'Ação permanente',
        'demands.deleteTitle': 'Remover demanda',
        'demands.close': 'Fechar',
        'demands.deleteQuestion': 'Retirar este item da fila?',
        'demands.deleteDescriptionStart': 'A demanda',
        'demands.deleteDescriptionEnd': 'será removida permanentemente. Esta ação não poderá ser desfeita.',
        'demands.keep': 'Manter demanda',
        'demands.deleting': 'Removendo...',
        'demands.remove': 'Remover demanda',
        'demands.loadError': 'Não foi possível carregar suas demandas.',
        'demands.searchError': 'Não foi possível pesquisar suas demandas.',
        'demands.registerError': 'Não foi possível registrar a demanda.',
        'demands.editError': 'Não foi possível editar a demanda.',
        'demands.deleteError': 'Não foi possível excluir a demanda.',
        'demands.observationAddError': 'Não foi possível adicionar a observação.',
        'demands.changeSubdomainError': 'Não foi possível atualizar a demanda para outro subdomínio.',
        'demands.changeSubdomain': 'Alterar subdomínio da demanda',
        'demands.changeSubdomainKicker': 'Transferir demanda',
        'demands.changeSubdomainTitle': 'Alterar subdomínio',
        'demands.changeSubdomainDescription': 'Selecione o novo subdomínio dono da demanda',
        'demands.destinationSubdomain': 'Subdomínio de destino',
        'demands.selectDestinationSubdomain': 'Selecione um subdomínio',
        'demands.confirmSubdomainChange': 'Alterar subdomínio',
        'demands.changingSubdomain': 'Alterando...',
        'demands.cancel': 'Cancelar',
        'accessDenied.kicker': 'Acesso restrito',
        'accessDenied.title': 'Este recurso não está disponível no seu plano.',
        'accessDenied.description': 'Seu usuário está autenticado, mas o plano contratado não libera esta área do Workhub.',
        'accessDenied.primaryAction': 'Voltar',
        'accessDenied.secondaryAction': 'Ir para o início',
        'daily.nav': 'Daily',
        'daily.clearSearch': 'Limpar pesquisa',
        'daily.personalPanel': 'Registro pessoal',
        'daily.heading': 'Daily sem',
        'daily.headingEmphasis': 'improviso.',
        'daily.intro': 'Anote o que avançou e chegue na daily com clareza.',
        'daily.register': 'Registrar daily',
        'daily.currentSlice': 'Recorte da daily',
        'daily.items': 'Registros',
        'daily.today': 'Hoje',
        'daily.thisWeek': 'Semana',
        'daily.words': 'Palavras',
        'daily.lastRecord': 'Último',
        'daily.period': 'Período',
        'daily.startDate': 'Início',
        'daily.endDate': 'Fim',
        'daily.boardKicker': 'Histórico',
        'daily.boardTitle': 'O que você fez',
        'daily.refresh': 'Atualizar registros',
        'daily.loading': 'Carregando registros...',
        'daily.emptyTitle': 'Nenhuma daily registrada.',
        'daily.emptyDescription': 'Use o formulário para guardar seu resumo do dia.',
        'daily.newKicker': 'Preparação',
        'daily.new': 'Novo registro',
        'daily.newDescription': 'Escreva em bullets ou em texto corrido. O importante é recuperar rápido na reunião.',
        'daily.date': 'Data',
        'daily.summary': 'Resumo do que você fez no dia',
        'daily.summaryPlaceholder': 'Ex.: Finalizei a tela de login, revisei o contrato do endpoint e hoje vou validar a integração.',
        'daily.save': 'Salvar daily',
        'daily.footerTagline': 'Seu roteiro antes da reunião.',
        'daily.footerText': 'Registre o avanço. Fale com contexto.',
        'daily.backToTop': 'Voltar ao topo',
        'daily.createdAt': 'Criado em',
        'daily.noCreatedAt': 'Sem data de criação',
        'daily.loadError': 'Não foi possível carregar suas dailies.',
        'daily.registerError': 'Não foi possível registrar a daily.',
        'daily.registerSuccess': 'Daily registrada com sucesso.',
        'feedback.nav': 'Feedback',
        'feedback.personalPanel': 'Registro pessoal',
        'feedback.heading': 'Feedbacks em',
        'feedback.headingEmphasis': 'ordem.',
        'feedback.intro': 'Registre quem aplicou feedback e mantenha o histórico acessível.',
        'feedback.register': 'Registrar feedback',
        'feedback.currentSlice': 'Recorte de feedback',
        'feedback.items': 'Registros',
        'feedback.today': 'Hoje',
        'feedback.people': 'Pessoas',
        'feedback.lastRecord': 'Último',
        'feedback.boardKicker': 'Histórico',
        'feedback.boardTitle': 'Feedbacks recebidos',
        'feedback.refresh': 'Atualizar feedbacks',
        'feedback.loading': 'Carregando feedbacks...',
        'feedback.emptyTitle': 'Nenhum feedback registrado.',
        'feedback.emptyDescription': 'Use o formulário para guardar o feedback recebido.',
        'feedback.newKicker': 'Entrada rápida',
        'feedback.new': 'Novo feedback',
        'feedback.newDescription': 'Informe a data, o feedback recebido e a pessoa que aplicou.',
        'feedback.date': 'Data',
        'feedback.summary': 'Feedback recebido',
        'feedback.summaryPlaceholder': 'Ex.: Melhorar clareza nos handoffs e manter os critérios de aceite mais objetivos.',
        'feedback.peopleFeedback': 'Pessoa que aplicou o feedback',
        'feedback.peopleFeedbackPlaceholder': 'Ex.: Feedback',
        'feedback.save': 'Salvar feedback',
        'feedback.footerTagline': 'Seu histórico de feedbacks.',
        'feedback.footerText': 'Registre conversas. Preserve contexto.',
        'feedback.backToTop': 'Voltar ao topo',
        'feedback.createdAt': 'Criado em',
        'feedback.noCreatedAt': 'Sem data de criação',
        'feedback.loadError': 'Não foi possível carregar seus feedbacks.',
        'feedback.registerError': 'Não foi possível registrar o feedback.',
        'feedback.registerSuccess': 'Feedback registrado com sucesso.',
        'subdomain.nav': 'Subdomínio',
        'subdomain.panel': 'Configuração',
        'subdomain.heading': 'Subdomínio',
        'subdomain.headingEmphasis': 'registrado.',
        'subdomain.intro': 'Cadastre o identificador público e a imagem que representam este espaço.',
        'subdomain.previewKicker': 'Prévia',
        'subdomain.previewTitle': 'Identidade do espaço',
        'subdomain.readyToRegister': 'Pronto para registrar',
        'subdomain.namePreview': 'Nome do subdomínio',
        'subdomain.previewDescription': 'A prévia usa os dados preenchidos no formulário antes do envio ao backend.',
        'subdomain.photoAlt': 'Imagem do subdomínio',
        'subdomain.formKicker': 'Registro',
        'subdomain.formTitle': 'Novo subdomínio',
        'subdomain.formDescription': 'Informe o nome obrigatório e, se houver, a URL da imagem.',
        'subdomain.name': 'Nome',
        'subdomain.namePlaceholder': 'Ex.: engenharia',
        'subdomain.urlPhoto': 'URL da imagem',
        'subdomain.urlPhotoPlaceholder': 'https://exemplo.com/logo.png',
        'subdomain.save': 'Registrar subdomínio',
        'subdomain.select': 'Selecionar subdomínio',
        'subdomain.selectPlaceholder': 'Subdomínio',
        'subdomain.loadError': 'Não foi possível carregar seus subdomínios.',
        'subdomain.footerTagline': 'Identidade do seu espaço.',
        'subdomain.footerText': 'Mantenha o endereço público alinhado com a operação.',
        'subdomain.registerError': 'Não foi possível registrar o subdomínio.',
        'subdomain.registerSuccess': 'Subdomínio registrado com sucesso.',
        'status.PENDING': 'Pendente',
        'status.ONGOING': 'Em andamento',
        'status.BLOCKED': 'Bloqueada',
        'status.DONE': 'Concluída',
        'priority.LOW': 'Baixa',
        'priority.MEDIUM': 'Média',
        'priority.HIGH': 'Alta',
        'priority.URGENT': 'Urgente',
    },
    en: {
        'language.label': 'Language',
        'language.pt-BR': 'Portuguese - BR',
        'language.en': 'English',
        'language.es': 'Spanish',
        'theme.light': 'Enable light mode',
        'theme.dark': 'Enable dark mode',
        'auth.bannerAlt': 'Workhub, a complete hub to organize, collaborate and deliver more.',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'you@company.com',
        'auth.password': 'Password',
        'auth.passwordPlaceholder': 'Your password',
        'auth.login.eyebrow': 'Login',
        'auth.login.title': 'Access your account',
        'auth.login.description': 'Sign in to keep track of your tasks, projects and deliveries.',
        'auth.login.submit': 'Sign in',
        'auth.login.noAccount': "Don't have an account yet?",
        'auth.login.createAccount': 'Create account',
        'auth.register.eyebrow': 'Registration',
        'auth.register.title': 'Create your account',
        'auth.register.description': 'After registration, you will be signed in to Workhub.',
        'auth.register.firstName': 'First name',
        'auth.register.firstNamePlaceholder': 'Your first name',
        'auth.register.lastName': 'Last name',
        'auth.register.lastNamePlaceholder': 'Your last name',
        'auth.register.username': 'Username',
        'auth.register.passwordPlaceholder': 'At least 8 characters',
        'auth.register.submit': 'Create account',
        'auth.register.hasAccount': 'Already have an account?',
        'auth.register.signIn': 'Sign in',
        'validation.email': 'Enter a valid email.',
        'validation.passwordRequired': 'Enter your password.',
        'validation.passwordMin': 'The password must have at least 8 characters.',
        'validation.usernameMin': 'The username must have at least 2 characters.',
        'validation.usernameMax': 'The username must have at most 30 characters.',
        'validation.lastNameMin': 'The last name must have at least 2 characters.',
        'validation.lastNameMax': 'The last name must have at most 30 characters.',
        'validation.firstNameMin': 'The first name must have at least 2 characters.',
        'validation.firstNameMax': 'The first name must have at most 20 characters.',
        'toast.success': 'Operation completed',
        'toast.error': 'Could not complete operation',
        'auth.register.success': 'User registered successfully!',
        'auth.register.error': 'An error occurred during registration. Please try again later!',
        'auth.login.success': 'Login successful!',
        'auth.login.error': 'Invalid email or password.',
        'demands.nav': 'Tasks',
        'demands.mainNav': 'Main navigation',
        'demands.user': 'User',
        'demands.search': 'Search tasks',
        'demands.searchPlaceholder': 'Search by title',
        'demands.clearSearch': 'Clear search',
        'demands.logout': 'Sign out',
        'demands.personalPanel': 'Personal dashboard',
        'demands.heading': 'Tasks in',
        'demands.headingEmphasis': 'motion.',
        'demands.intro': 'A direct view of the work that needs to move forward.',
        'demands.register': 'Add task',
        'demands.currentSlice': 'Current snapshot',
        'demands.items': 'Items',
        'demands.ongoing': 'Ongoing',
        'demands.urgent': 'Urgent',
        'demands.overdue': 'Overdue',
        'demands.closed': 'Closed',
        'demands.queue': 'Work queue',
        'demands.onTable': 'What is on the table',
        'demands.boardKicker': 'Status view',
        'demands.boardTitle': 'Task board',
        'demands.addToColumn': 'Add to',
        'demands.emptyColumn': 'No tasks in this status.',
        'demands.moveSuccess': 'Task status updated.',
        'demands.moveError': 'Could not move the task.',
        'demands.filterByStatus': 'Filter by status',
        'demands.allStatus': 'All status',
        'demands.filterByPriority': 'Filter by priority',
        'demands.allPriorities': 'All priorities',
        'demands.refresh': 'Refresh tasks',
        'demands.loading': 'Refreshing queue...',
        'demands.emptyTitle': 'Queue clear.',
        'demands.emptyDescription': 'Add the next task to get work moving.',
        'demands.noDeadline': 'No deadline set',
        'demands.notFinalized': 'Not finalized',
        'demands.edit': 'Edit task',
        'demands.delete': 'Delete task',
        'demands.viewDetails': 'View task details',
        'demands.detailsKicker': 'Task details',
        'demands.createdAt': 'Created at',
        'demands.updatedAt': 'Last updated',
        'demands.neverUpdated': 'Not updated yet',
        'demands.page': 'Page',
        'demands.of': 'of',
        'demands.previousPage': 'Previous page',
        'demands.nextPage': 'Next page',
        'demands.editKicker': 'Course correction',
        'demands.newKicker': 'Quick entry',
        'demands.new': 'New task',
        'demands.editDescription': 'Update the record as the work moves forward.',
        'demands.newDescription': 'Capture now. Refine while executing.',
        'demands.backToBoard': 'Back to board',
        'demands.createHeading': 'Turn a need into clear work.',
        'demands.createDescription': 'Record the essential context so the task can move forward without depending on scattered information.',
        'demands.createHintContext': 'Explain the expected outcome',
        'demands.createHintPriority': 'Set priority and initial status',
        'demands.createHintDeadline': 'Add a deadline when needed',
        'demands.cancelCreate': 'Cancel',
        'demands.title': 'Title',
        'demands.titlePlaceholder': 'E.g.: Review customer endpoint',
        'demands.description': 'Description',
        'demands.descriptionPlaceholder': 'Describe what needs to be done',
        'demands.reviewNote': 'Review note',
        'demands.optional': 'optional',
        'demands.reviewNotePlaceholder': 'Record context, decisions or the expected result for review',
        'demands.observations': 'Notes',
        'demands.newObservations': 'New notes',
        'demands.existingObservations': 'Existing notes',
        'demands.observationPlaceholder': 'Write a note about this task',
        'demands.addObservation': 'Add note',
        'demands.addAnotherObservation': 'Add another note',
        'demands.saveObservations': 'Save notes',
        'demands.removeObservation': 'Remove note',
        'demands.noObservations': 'No notes recorded.',
        'demands.deadline': 'Deadline',
        'demands.finalizedAt': 'Finalized at',
        'demands.status': 'Status',
        'demands.priority': 'Priority',
        'demands.save': 'Save changes',
        'demands.cancelEdit': 'Cancel editing',
        'demands.footerTagline': 'Your daily delivery log.',
        'demands.footerText': 'Organize the present. Document progress.',
        'demands.backToTop': 'Back to top',
        'demands.deleteKicker': 'Permanent action',
        'demands.deleteTitle': 'Remove task',
        'demands.close': 'Close',
        'demands.deleteQuestion': 'Remove this item from the queue?',
        'demands.deleteDescriptionStart': 'The task',
        'demands.deleteDescriptionEnd': 'will be permanently removed. This action cannot be undone.',
        'demands.keep': 'Keep task',
        'demands.deleting': 'Removing...',
        'demands.remove': 'Remove task',
        'demands.loadError': 'Could not load your tasks.',
        'demands.searchError': 'Could not search your tasks.',
        'demands.registerError': 'Could not add the task.',
        'demands.editError': 'Could not edit the task.',
        'demands.deleteError': 'Could not delete the task.',
        'demands.observationAddError': 'Could not add the note.',
        'demands.changeSubdomainError': 'Could not move the task to another subdomain.',
        'demands.changeSubdomain': 'Change task subdomain',
        'demands.changeSubdomainKicker': 'Transfer task',
        'demands.changeSubdomainTitle': 'Change subdomain',
        'demands.changeSubdomainDescription': 'Select the new subdomain that will own the task',
        'demands.destinationSubdomain': 'Destination subdomain',
        'demands.selectDestinationSubdomain': 'Select a subdomain',
        'demands.confirmSubdomainChange': 'Change subdomain',
        'demands.changingSubdomain': 'Changing...',
        'demands.cancel': 'Cancel',
        'accessDenied.kicker': 'Restricted access',
        'accessDenied.title': 'This resource is not available in your plan.',
        'accessDenied.description': 'Your user is authenticated, but the contracted plan does not unlock this Workhub area.',
        'accessDenied.primaryAction': 'Go back',
        'accessDenied.secondaryAction': 'Go to start',
        'daily.nav': 'Daily',
        'daily.clearSearch': 'Clear search',
        'daily.personalPanel': 'Personal record',
        'daily.heading': 'Daily without',
        'daily.headingEmphasis': 'guesswork.',
        'daily.intro': 'Write down what moved forward and join daily with clarity.',
        'daily.register': 'Add daily',
        'daily.currentSlice': 'Daily snapshot',
        'daily.items': 'Records',
        'daily.today': 'Today',
        'daily.thisWeek': 'Week',
        'daily.words': 'Words',
        'daily.lastRecord': 'Latest',
        'daily.period': 'Period',
        'daily.startDate': 'Start',
        'daily.endDate': 'End',
        'daily.boardKicker': 'History',
        'daily.boardTitle': 'What you did',
        'daily.refresh': 'Refresh records',
        'daily.loading': 'Loading records...',
        'daily.emptyTitle': 'No daily records yet.',
        'daily.emptyDescription': 'Use the form to save your day summary.',
        'daily.newKicker': 'Preparation',
        'daily.new': 'New record',
        'daily.newDescription': 'Write bullets or plain text. The point is quick recall during the meeting.',
        'daily.date': 'Date',
        'daily.summary': 'Summary of what you did today',
        'daily.summaryPlaceholder': 'E.g.: Finished the login screen, reviewed the endpoint contract and today I will validate the integration.',
        'daily.save': 'Save daily',
        'daily.footerTagline': 'Your script before the meeting.',
        'daily.footerText': 'Record progress. Speak with context.',
        'daily.backToTop': 'Back to top',
        'daily.createdAt': 'Created at',
        'daily.noCreatedAt': 'No creation date',
        'daily.loadError': 'Could not load your daily records.',
        'daily.registerError': 'Could not add the daily record.',
        'daily.registerSuccess': 'Daily recorded successfully.',
        'feedback.nav': 'Feedback',
        'feedback.personalPanel': 'Personal record',
        'feedback.heading': 'Feedback in',
        'feedback.headingEmphasis': 'order.',
        'feedback.intro': 'Record who gave feedback and keep the history accessible.',
        'feedback.register': 'Add feedback',
        'feedback.currentSlice': 'Feedback snapshot',
        'feedback.items': 'Records',
        'feedback.today': 'Today',
        'feedback.people': 'People',
        'feedback.lastRecord': 'Latest',
        'feedback.boardKicker': 'History',
        'feedback.boardTitle': 'Feedback received',
        'feedback.refresh': 'Refresh feedback',
        'feedback.loading': 'Loading feedback...',
        'feedback.emptyTitle': 'No feedback records yet.',
        'feedback.emptyDescription': 'Use the form to save the feedback received.',
        'feedback.newKicker': 'Quick entry',
        'feedback.new': 'New feedback',
        'feedback.newDescription': 'Enter the date, the feedback received and the person who gave it.',
        'feedback.date': 'Date',
        'feedback.summary': 'Feedback received',
        'feedback.summaryPlaceholder': 'E.g.: Improve clarity in handoffs and keep acceptance criteria more objective.',
        'feedback.peopleFeedback': 'Person who gave feedback',
        'feedback.peopleFeedbackPlaceholder': 'E.g.: Feedback',
        'feedback.save': 'Save feedback',
        'feedback.footerTagline': 'Your feedback history.',
        'feedback.footerText': 'Record conversations. Preserve context.',
        'feedback.backToTop': 'Back to top',
        'feedback.createdAt': 'Created at',
        'feedback.noCreatedAt': 'No creation date',
        'feedback.loadError': 'Could not load your feedback records.',
        'feedback.registerError': 'Could not add the feedback record.',
        'feedback.registerSuccess': 'Feedback recorded successfully.',
        'subdomain.nav': 'Subdomain',
        'subdomain.panel': 'Configuration',
        'subdomain.heading': 'Subdomain',
        'subdomain.headingEmphasis': 'registered.',
        'subdomain.intro': 'Register the public identifier and image that represent this workspace.',
        'subdomain.previewKicker': 'Preview',
        'subdomain.previewTitle': 'Workspace identity',
        'subdomain.readyToRegister': 'Ready to register',
        'subdomain.namePreview': 'Subdomain name',
        'subdomain.previewDescription': 'The preview uses the data entered in the form before sending it to the backend.',
        'subdomain.photoAlt': 'Subdomain image',
        'subdomain.formKicker': 'Registration',
        'subdomain.formTitle': 'New subdomain',
        'subdomain.formDescription': 'Enter the required name and, if available, the image URL.',
        'subdomain.name': 'Name',
        'subdomain.namePlaceholder': 'E.g.: engineering',
        'subdomain.urlPhoto': 'Image URL',
        'subdomain.urlPhotoPlaceholder': 'https://example.com/logo.png',
        'subdomain.save': 'Register subdomain',
        'subdomain.select': 'Select subdomain',
        'subdomain.selectPlaceholder': 'Subdomain',
        'subdomain.loadError': 'Could not load your subdomains.',
        'subdomain.footerTagline': 'Your workspace identity.',
        'subdomain.footerText': 'Keep the public address aligned with the operation.',
        'subdomain.registerError': 'Could not register the subdomain.',
        'subdomain.registerSuccess': 'Subdomain registered successfully.',
        'status.PENDING': 'Pending',
        'status.ONGOING': 'Ongoing',
        'status.BLOCKED': 'Blocked',
        'status.DONE': 'Completed',
        'priority.LOW': 'Low',
        'priority.MEDIUM': 'Medium',
        'priority.HIGH': 'High',
        'priority.URGENT': 'Urgent',
    },
    es: {
        'language.label': 'Idioma',
        'language.pt-BR': 'Portugués - BR',
        'language.en': 'Inglés',
        'language.es': 'Español',
        'theme.light': 'Activar modo claro',
        'theme.dark': 'Activar modo oscuro',
        'auth.bannerAlt': 'Workhub, un hub completo para organizar, colaborar y entregar más.',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'tu@empresa.com',
        'auth.password': 'Contraseña',
        'auth.passwordPlaceholder': 'Tu contraseña',
        'auth.login.eyebrow': 'Login',
        'auth.login.title': 'Accede a tu cuenta',
        'auth.login.description': 'Inicia sesión para seguir tus tareas, proyectos y entregas.',
        'auth.login.submit': 'Entrar',
        'auth.login.noAccount': '¿Aún no tienes una cuenta?',
        'auth.login.createAccount': 'Crear cuenta',
        'auth.register.eyebrow': 'Registro',
        'auth.register.title': 'Crea tu cuenta',
        'auth.register.description': 'Después del registro, iniciarás sesión en Workhub.',
        'auth.register.firstName': 'Nombre',
        'auth.register.firstNamePlaceholder': 'Tu nombre',
        'auth.register.lastName': 'Apellido',
        'auth.register.lastNamePlaceholder': 'Tu apellido',
        'auth.register.username': 'Username',
        'auth.register.passwordPlaceholder': 'Mínimo de 8 caracteres',
        'auth.register.submit': 'Crear cuenta',
        'auth.register.hasAccount': '¿Ya tienes una cuenta?',
        'auth.register.signIn': 'Entrar',
        'validation.email': 'Ingresa un email válido.',
        'validation.passwordRequired': 'Ingresa tu contraseña.',
        'validation.passwordMin': 'La contraseña debe tener al menos 8 caracteres.',
        'validation.usernameMin': 'El username debe tener al menos 2 caracteres.',
        'validation.usernameMax': 'El username debe tener como máximo 30 caracteres.',
        'validation.lastNameMin': 'El apellido debe tener al menos 2 caracteres.',
        'validation.lastNameMax': 'El apellido debe tener como máximo 30 caracteres.',
        'validation.firstNameMin': 'El nombre debe tener al menos 2 caracteres.',
        'validation.firstNameMax': 'El nombre debe tener como máximo 20 caracteres.',
        'toast.success': 'Operación completada',
        'toast.error': 'No se pudo completar',
        'auth.register.success': '¡Usuario registrado con éxito!',
        'auth.register.error': 'Ocurrió un error durante el registro. ¡Inténtalo de nuevo más tarde!',
        'auth.login.success': '¡Inicio de sesión exitoso!',
        'auth.login.error': 'Email o contraseña inválidos.',
        'demands.nav': 'Tareas',
        'demands.mainNav': 'Navegación principal',
        'demands.user': 'Usuario',
        'demands.search': 'Buscar tareas',
        'demands.searchPlaceholder': 'Buscar por título',
        'demands.clearSearch': 'Limpiar búsqueda',
        'demands.logout': 'Salir',
        'demands.personalPanel': 'Panel personal',
        'demands.heading': 'Tareas en',
        'demands.headingEmphasis': 'movimiento.',
        'demands.intro': 'Una visión directa del trabajo que debe avanzar.',
        'demands.register': 'Registrar tarea',
        'demands.currentSlice': 'Recorte actual',
        'demands.items': 'Ítems',
        'demands.ongoing': 'En curso',
        'demands.urgent': 'Urgentes',
        'demands.overdue': 'Atrasadas',
        'demands.closed': 'Cerradas',
        'demands.queue': 'Cola de trabajo',
        'demands.onTable': 'Lo que está sobre la mesa',
        'demands.boardKicker': 'Vista por status',
        'demands.boardTitle': 'Board de tareas',
        'demands.addToColumn': 'Añadir en',
        'demands.emptyColumn': 'No hay tareas en este status.',
        'demands.moveSuccess': 'Status de la tarea actualizado.',
        'demands.moveError': 'No se pudo mover la tarea.',
        'demands.filterByStatus': 'Filtrar por status',
        'demands.allStatus': 'Todos los status',
        'demands.filterByPriority': 'Filtrar por prioridad',
        'demands.allPriorities': 'Todas las prioridades',
        'demands.refresh': 'Actualizar tareas',
        'demands.loading': 'Actualizando la cola...',
        'demands.emptyTitle': 'Cola libre.',
        'demands.emptyDescription': 'Registra la próxima tarea para poner el trabajo en movimiento.',
        'demands.noDeadline': 'Sin plazo definido',
        'demands.notFinalized': 'No finalizada',
        'demands.edit': 'Editar tarea',
        'demands.delete': 'Eliminar tarea',
        'demands.viewDetails': 'Ver detalles de la tarea',
        'demands.detailsKicker': 'Detalles de la tarea',
        'demands.createdAt': 'Creada el',
        'demands.updatedAt': 'Última actualización',
        'demands.neverUpdated': 'Aún no actualizada',
        'demands.page': 'Página',
        'demands.of': 'de',
        'demands.previousPage': 'Página anterior',
        'demands.nextPage': 'Página siguiente',
        'demands.editKicker': 'Ajuste de ruta',
        'demands.newKicker': 'Entrada rápida',
        'demands.new': 'Nueva tarea',
        'demands.editDescription': 'Actualiza el registro a medida que avanza el trabajo.',
        'demands.newDescription': 'Captura ahora. Refina mientras ejecutas.',
        'demands.backToBoard': 'Volver al board',
        'demands.createHeading': 'Convierte una necesidad en trabajo claro.',
        'demands.createDescription': 'Registra el contexto esencial para que la tarea pueda avanzar sin depender de información dispersa.',
        'demands.createHintContext': 'Explica el resultado esperado',
        'demands.createHintPriority': 'Define prioridad y status inicial',
        'demands.createHintDeadline': 'Informa un plazo cuando sea necesario',
        'demands.cancelCreate': 'Cancelar',
        'demands.title': 'Título',
        'demands.titlePlaceholder': 'Ej.: Revisar endpoint de clientes',
        'demands.description': 'Descripción',
        'demands.descriptionPlaceholder': 'Describe lo que debe realizarse',
        'demands.reviewNote': 'Nota para review',
        'demands.optional': 'opcional',
        'demands.reviewNotePlaceholder': 'Registra contexto, decisiones o el resultado esperado para consultar en el review',
        'demands.observations': 'Observaciones',
        'demands.newObservations': 'Nuevas observaciones',
        'demands.existingObservations': 'Observaciones existentes',
        'demands.observationPlaceholder': 'Escribe una observación sobre esta tarea',
        'demands.addObservation': 'Añadir observación',
        'demands.addAnotherObservation': 'Añadir otra observación',
        'demands.saveObservations': 'Guardar observaciones',
        'demands.removeObservation': 'Eliminar observación',
        'demands.noObservations': 'No hay observaciones registradas.',
        'demands.deadline': 'Plazo',
        'demands.finalizedAt': 'Finalizada el',
        'demands.status': 'Status',
        'demands.priority': 'Prioridad',
        'demands.save': 'Guardar cambios',
        'demands.cancelEdit': 'Cancelar edición',
        'demands.footerTagline': 'Tu registro diario de entregas.',
        'demands.footerText': 'Organiza el presente. Documenta lo que avanzó.',
        'demands.backToTop': 'Volver arriba',
        'demands.deleteKicker': 'Acción permanente',
        'demands.deleteTitle': 'Eliminar tarea',
        'demands.close': 'Cerrar',
        'demands.deleteQuestion': '¿Retirar este ítem de la cola?',
        'demands.deleteDescriptionStart': 'La tarea',
        'demands.deleteDescriptionEnd': 'será eliminada permanentemente. Esta acción no se puede deshacer.',
        'demands.keep': 'Mantener tarea',
        'demands.deleting': 'Eliminando...',
        'demands.remove': 'Eliminar tarea',
        'demands.loadError': 'No se pudieron cargar tus tareas.',
        'demands.searchError': 'No se pudieron buscar tus tareas.',
        'demands.registerError': 'No se pudo registrar la tarea.',
        'demands.editError': 'No se pudo editar la tarea.',
        'demands.deleteError': 'No se pudo eliminar la tarea.',
        'demands.observationAddError': 'No se pudo añadir la observación.',
        'demands.changeSubdomainError': 'No se pudo mover la tarea a otro subdominio.',
        'demands.changeSubdomain': 'Cambiar subdominio de la tarea',
        'demands.changeSubdomainKicker': 'Transferir tarea',
        'demands.changeSubdomainTitle': 'Cambiar subdominio',
        'demands.changeSubdomainDescription': 'Selecciona el nuevo subdominio propietario de la tarea',
        'demands.destinationSubdomain': 'Subdominio de destino',
        'demands.selectDestinationSubdomain': 'Selecciona un subdominio',
        'demands.confirmSubdomainChange': 'Cambiar subdominio',
        'demands.changingSubdomain': 'Cambiando...',
        'demands.cancel': 'Cancelar',
        'accessDenied.kicker': 'Acceso restringido',
        'accessDenied.title': 'Este recurso no está disponible en tu plan.',
        'accessDenied.description': 'Tu usuario está autenticado, pero el plan contratado no habilita esta área de Workhub.',
        'accessDenied.primaryAction': 'Volver',
        'accessDenied.secondaryAction': 'Ir al inicio',
        'daily.nav': 'Daily',
        'daily.clearSearch': 'Limpiar búsqueda',
        'daily.personalPanel': 'Registro personal',
        'daily.heading': 'Daily sin',
        'daily.headingEmphasis': 'improvisar.',
        'daily.intro': 'Anota lo que avanzó y llega a la daily con claridad.',
        'daily.register': 'Registrar daily',
        'daily.currentSlice': 'Recorte de daily',
        'daily.items': 'Registros',
        'daily.today': 'Hoy',
        'daily.thisWeek': 'Semana',
        'daily.words': 'Palabras',
        'daily.lastRecord': 'Último',
        'daily.period': 'Período',
        'daily.startDate': 'Inicio',
        'daily.endDate': 'Fin',
        'daily.boardKicker': 'Historial',
        'daily.boardTitle': 'Lo que hiciste',
        'daily.refresh': 'Actualizar registros',
        'daily.loading': 'Cargando registros...',
        'daily.emptyTitle': 'No hay dailies registradas.',
        'daily.emptyDescription': 'Usa el formulario para guardar tu resumen del día.',
        'daily.newKicker': 'Preparación',
        'daily.new': 'Nuevo registro',
        'daily.newDescription': 'Escribe en bullets o texto corrido. Lo importante es recordar rápido en la reunión.',
        'daily.date': 'Fecha',
        'daily.summary': 'Resumen de lo que hiciste en el día',
        'daily.summaryPlaceholder': 'Ej.: Finalicé la pantalla de login, revisé el contrato del endpoint y hoy validaré la integración.',
        'daily.save': 'Guardar daily',
        'daily.footerTagline': 'Tu guion antes de la reunión.',
        'daily.footerText': 'Registra el avance. Habla con contexto.',
        'daily.backToTop': 'Volver arriba',
        'daily.createdAt': 'Creado el',
        'daily.noCreatedAt': 'Sin fecha de creación',
        'daily.loadError': 'No se pudieron cargar tus dailies.',
        'daily.registerError': 'No se pudo registrar la daily.',
        'daily.registerSuccess': 'Daily registrada con éxito.',
        'feedback.nav': 'Feedback',
        'feedback.personalPanel': 'Registro personal',
        'feedback.heading': 'Feedbacks en',
        'feedback.headingEmphasis': 'orden.',
        'feedback.intro': 'Registra quién aplicó feedback y mantén el historial accesible.',
        'feedback.register': 'Registrar feedback',
        'feedback.currentSlice': 'Recorte de feedback',
        'feedback.items': 'Registros',
        'feedback.today': 'Hoy',
        'feedback.people': 'Personas',
        'feedback.lastRecord': 'Último',
        'feedback.boardKicker': 'Historial',
        'feedback.boardTitle': 'Feedbacks recibidos',
        'feedback.refresh': 'Actualizar feedbacks',
        'feedback.loading': 'Cargando feedbacks...',
        'feedback.emptyTitle': 'No hay feedbacks registrados.',
        'feedback.emptyDescription': 'Usa el formulario para guardar el feedback recibido.',
        'feedback.newKicker': 'Entrada rápida',
        'feedback.new': 'Nuevo feedback',
        'feedback.newDescription': 'Informa la fecha, el feedback recibido y la persona que lo aplicó.',
        'feedback.date': 'Fecha',
        'feedback.summary': 'Feedback recibido',
        'feedback.summaryPlaceholder': 'Ej.: Mejorar claridad en los handoffs y mantener criterios de aceptación más objetivos.',
        'feedback.peopleFeedback': 'Persona que aplicó el feedback',
        'feedback.peopleFeedbackPlaceholder': 'Ej.: Feedback',
        'feedback.save': 'Guardar feedback',
        'feedback.footerTagline': 'Tu historial de feedbacks.',
        'feedback.footerText': 'Registra conversaciones. Preserva contexto.',
        'feedback.backToTop': 'Volver arriba',
        'feedback.createdAt': 'Creado el',
        'feedback.noCreatedAt': 'Sin fecha de creación',
        'feedback.loadError': 'No se pudieron cargar tus feedbacks.',
        'feedback.registerError': 'No se pudo registrar el feedback.',
        'feedback.registerSuccess': 'Feedback registrado con éxito.',
        'subdomain.nav': 'Subdominio',
        'subdomain.panel': 'Configuración',
        'subdomain.heading': 'Subdominio',
        'subdomain.headingEmphasis': 'registrado.',
        'subdomain.intro': 'Registra el identificador público y la imagen que representan este espacio.',
        'subdomain.previewKicker': 'Vista previa',
        'subdomain.previewTitle': 'Identidad del espacio',
        'subdomain.readyToRegister': 'Listo para registrar',
        'subdomain.namePreview': 'Nombre del subdominio',
        'subdomain.previewDescription': 'La vista previa usa los datos del formulario antes de enviarlos al backend.',
        'subdomain.photoAlt': 'Imagen del subdominio',
        'subdomain.formKicker': 'Registro',
        'subdomain.formTitle': 'Nuevo subdominio',
        'subdomain.formDescription': 'Informa el nombre obligatorio y, si existe, la URL de la imagen.',
        'subdomain.name': 'Nombre',
        'subdomain.namePlaceholder': 'Ej.: ingenieria',
        'subdomain.urlPhoto': 'URL de la imagen',
        'subdomain.urlPhotoPlaceholder': 'https://ejemplo.com/logo.png',
        'subdomain.save': 'Registrar subdominio',
        'subdomain.select': 'Seleccionar subdominio',
        'subdomain.selectPlaceholder': 'Subdominio',
        'subdomain.loadError': 'No se pudieron cargar tus subdominios.',
        'subdomain.footerTagline': 'Identidad de tu espacio.',
        'subdomain.footerText': 'Mantén la dirección pública alineada con la operación.',
        'subdomain.registerError': 'No se pudo registrar el subdominio.',
        'subdomain.registerSuccess': 'Subdominio registrado con éxito.',
        'status.PENDING': 'Pendiente',
        'status.ONGOING': 'En curso',
        'status.BLOCKED': 'Bloqueada',
        'status.DONE': 'Completada',
        'priority.LOW': 'Baja',
        'priority.MEDIUM': 'Media',
        'priority.HIGH': 'Alta',
        'priority.URGENT': 'Urgente',
    },
} as const;

export type TranslationKey = keyof typeof messages['pt-BR'];

const language = ref<Language>('pt-BR');

const getPreferredLanguage = (): Language => {
    const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);

    if (storedLanguage === 'pt-BR' || storedLanguage === 'en' || storedLanguage === 'es')
        return storedLanguage;

    if (navigator.language.toLowerCase().startsWith('es'))
        return 'es';

    return navigator.language.toLowerCase().startsWith('en') ? 'en' : 'pt-BR';
};

const applyLanguage = (value: Language) => {
    language.value = value;
    document.documentElement.lang = value;
};

export const initializeLanguage = () => applyLanguage(getPreferredLanguage());

export const translate = (key: TranslationKey) => messages[language.value][key];

export const useLanguage = () => {
    const setLanguage = (value: Language) => {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, value);
        applyLanguage(value);
    };

    return {
        language,
        setLanguage,
        t: translate,
    };
};
