import {ref} from 'vue';

export type Language = 'pt-BR' | 'en' | 'es';

const LANGUAGE_STORAGE_KEY = 'workhub-language';

const messages = {
    'pt-BR': {
        'language.label': 'Idioma',
        'language.pt-BR': 'Português - BR',
        'language.en': 'Inglês',
        'language.es': 'Espanhol',
        'theme.light': 'Ativar modo claro',
        'theme.dark': 'Ativar modo escuro',
        'auth.bannerAlt': 'Workhub, um hub completo para organizar, colaborar e entregar mais.',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'voce@empresa.com',
        'auth.password': 'Senha',
        'auth.passwordPlaceholder': 'Sua senha',
        'auth.login.eyebrow': 'Login',
        'auth.login.title': 'Acesse sua conta',
        'auth.login.description': 'Entre para continuar acompanhando suas tarefas, projetos e entregas.',
        'auth.login.submit': 'Entrar',
        'auth.login.noAccount': 'Ainda não tem uma conta?',
        'auth.login.createAccount': 'Criar conta',
        'auth.register.eyebrow': 'Cadastro',
        'auth.register.title': 'Crie sua conta',
        'auth.register.description': 'Depois do registro, você já entra autenticado no Workhub.',
        'auth.register.firstName': 'Nome',
        'auth.register.firstNamePlaceholder': 'Seu nome',
        'auth.register.lastName': 'Sobrenome',
        'auth.register.lastNamePlaceholder': 'Seu sobrenome',
        'auth.register.username': 'Username',
        'auth.register.passwordPlaceholder': 'Mínimo de 8 caracteres',
        'auth.register.submit': 'Criar conta',
        'auth.register.hasAccount': 'Já tem uma conta?',
        'auth.register.signIn': 'Entrar',
        'validation.email': 'Informe um email válido.',
        'validation.passwordRequired': 'Informe sua senha.',
        'validation.passwordMin': 'A senha deve ter pelo menos 8 caracteres.',
        'validation.usernameMin': 'O username deve ter pelo menos 2 caracteres.',
        'validation.usernameMax': 'O username deve ter no máximo 30 caracteres.',
        'validation.lastNameMin': 'O sobrenome deve ter pelo menos 2 caracteres.',
        'validation.lastNameMax': 'O sobrenome deve ter no máximo 30 caracteres.',
        'validation.firstNameMin': 'O nome deve ter pelo menos 2 caracteres.',
        'validation.firstNameMax': 'O nome deve ter no máximo 20 caracteres.',
        'toast.success': 'Operação concluída',
        'toast.error': 'Não foi possível concluir',
        'auth.register.success': 'Usuário registrado com sucesso!',
        'auth.register.error': 'Ocorreu um erro ao realizar o registro, tente novamente mais tarde!',
        'auth.login.success': 'Login realizado com sucesso!',
        'auth.login.error': 'Email ou senha inválidos.',
        'demands.nav': 'Demandas',
        'demands.mainNav': 'Navegação principal',
        'demands.user': 'Usuário',
        'demands.search': 'Pesquisar demandas',
        'demands.searchPlaceholder': 'Buscar por título',
        'demands.clearSearch': 'Limpar pesquisa',
        'demands.logout': 'Sair',
        'demands.personalPanel': 'Painel pessoal',
        'demands.heading': 'Demandas em',
        'demands.headingEmphasis': 'movimento.',
        'demands.intro': 'Uma visão direta do trabalho que precisa avançar.',
        'demands.register': 'Registrar demanda',
        'demands.currentSlice': 'Recorte atual',
        'demands.items': 'Itens',
        'demands.ongoing': 'Em curso',
        'demands.urgent': 'Urgentes',
        'demands.overdue': 'Atrasadas',
        'demands.closed': 'Fechadas',
        'demands.queue': 'Fila de trabalho',
        'demands.onTable': 'O que está na mesa',
        'demands.filterByStatus': 'Filtrar por status',
        'demands.allStatus': 'Todos os status',
        'demands.filterByPriority': 'Filtrar por prioridade',
        'demands.allPriorities': 'Todas as prioridades',
        'demands.refresh': 'Atualizar demandas',
        'demands.loading': 'Atualizando a fila...',
        'demands.emptyTitle': 'Fila livre.',
        'demands.emptyDescription': 'Registre a próxima demanda para colocar o trabalho em movimento.',
        'demands.noDeadline': 'Sem prazo definido',
        'demands.notFinalized': 'Não finalizada',
        'demands.edit': 'Editar demanda',
        'demands.delete': 'Excluir demanda',
        'demands.viewDetails': 'Ver detalhes da demanda',
        'demands.detailsKicker': 'Detalhes da demanda',
        'demands.createdAt': 'Criada em',
        'demands.page': 'Folha',
        'demands.of': 'de',
        'demands.previousPage': 'Página anterior',
        'demands.nextPage': 'Próxima página',
        'demands.editKicker': 'Ajuste de rota',
        'demands.newKicker': 'Entrada rápida',
        'demands.new': 'Nova demanda',
        'demands.editDescription': 'Atualize o registro conforme o trabalho avança.',
        'demands.newDescription': 'Capture agora. Refine enquanto executa.',
        'demands.title': 'Título',
        'demands.titlePlaceholder': 'Ex.: Revisar endpoint de clientes',
        'demands.description': 'Descrição',
        'demands.descriptionPlaceholder': 'Descreva o que precisa ser realizado',
        'demands.reviewNote': 'Anotação para review',
        'demands.optional': 'opcional',
        'demands.reviewNotePlaceholder': 'Registre contexto, decisões ou o resultado esperado para consultar no review',
        'demands.deadline': 'Prazo',
        'demands.finalizedAt': 'Finalizada em',
        'demands.status': 'Status',
        'demands.priority': 'Prioridade',
        'demands.save': 'Salvar alterações',
        'demands.cancelEdit': 'Cancelar edição',
        'demands.footerTagline': 'Seu registro diário de entregas.',
        'demands.footerText': 'Organize o presente. Documente o que avançou.',
        'demands.backToTop': 'Voltar ao topo',
        'demands.deleteKicker': 'Ação permanente',
        'demands.deleteTitle': 'Remover demanda',
        'demands.close': 'Fechar',
        'demands.deleteQuestion': 'Retirar este item da fila?',
        'demands.deleteDescriptionStart': 'A demanda',
        'demands.deleteDescriptionEnd': 'será removida permanentemente. Esta ação não poderá ser desfeita.',
        'demands.keep': 'Manter demanda',
        'demands.deleting': 'Removendo...',
        'demands.remove': 'Remover demanda',
        'demands.loadError': 'Não foi possível carregar suas demandas.',
        'demands.searchError': 'Não foi possível pesquisar suas demandas.',
        'demands.registerError': 'Não foi possível registrar a demanda.',
        'demands.editError': 'Não foi possível editar a demanda.',
        'demands.deleteError': 'Não foi possível excluir a demanda.',
        'status.PENDING': 'Pendente',
        'status.ONGOING': 'Em andamento',
        'status.BLOCKED': 'Bloqueada',
        'status.DONE': 'Concluída',
        'priority.LOW': 'Baixa',
        'priority.MEDIUM': 'Média',
        'priority.HIGH': 'Alta',
        'priority.URGENT': 'Urgente',
    },
    en: {
        'language.label': 'Language',
        'language.pt-BR': 'Portuguese - BR',
        'language.en': 'English',
        'language.es': 'Spanish',
        'theme.light': 'Enable light mode',
        'theme.dark': 'Enable dark mode',
        'auth.bannerAlt': 'Workhub, a complete hub to organize, collaborate and deliver more.',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'you@company.com',
        'auth.password': 'Password',
        'auth.passwordPlaceholder': 'Your password',
        'auth.login.eyebrow': 'Login',
        'auth.login.title': 'Access your account',
        'auth.login.description': 'Sign in to keep track of your tasks, projects and deliveries.',
        'auth.login.submit': 'Sign in',
        'auth.login.noAccount': "Don't have an account yet?",
        'auth.login.createAccount': 'Create account',
        'auth.register.eyebrow': 'Registration',
        'auth.register.title': 'Create your account',
        'auth.register.description': 'After registration, you will be signed in to Workhub.',
        'auth.register.firstName': 'First name',
        'auth.register.firstNamePlaceholder': 'Your first name',
        'auth.register.lastName': 'Last name',
        'auth.register.lastNamePlaceholder': 'Your last name',
        'auth.register.username': 'Username',
        'auth.register.passwordPlaceholder': 'At least 8 characters',
        'auth.register.submit': 'Create account',
        'auth.register.hasAccount': 'Already have an account?',
        'auth.register.signIn': 'Sign in',
        'validation.email': 'Enter a valid email.',
        'validation.passwordRequired': 'Enter your password.',
        'validation.passwordMin': 'The password must have at least 8 characters.',
        'validation.usernameMin': 'The username must have at least 2 characters.',
        'validation.usernameMax': 'The username must have at most 30 characters.',
        'validation.lastNameMin': 'The last name must have at least 2 characters.',
        'validation.lastNameMax': 'The last name must have at most 30 characters.',
        'validation.firstNameMin': 'The first name must have at least 2 characters.',
        'validation.firstNameMax': 'The first name must have at most 20 characters.',
        'toast.success': 'Operation completed',
        'toast.error': 'Could not complete operation',
        'auth.register.success': 'User registered successfully!',
        'auth.register.error': 'An error occurred during registration. Please try again later!',
        'auth.login.success': 'Login successful!',
        'auth.login.error': 'Invalid email or password.',
        'demands.nav': 'Tasks',
        'demands.mainNav': 'Main navigation',
        'demands.user': 'User',
        'demands.search': 'Search tasks',
        'demands.searchPlaceholder': 'Search by title',
        'demands.clearSearch': 'Clear search',
        'demands.logout': 'Sign out',
        'demands.personalPanel': 'Personal dashboard',
        'demands.heading': 'Tasks in',
        'demands.headingEmphasis': 'motion.',
        'demands.intro': 'A direct view of the work that needs to move forward.',
        'demands.register': 'Add task',
        'demands.currentSlice': 'Current snapshot',
        'demands.items': 'Items',
        'demands.ongoing': 'Ongoing',
        'demands.urgent': 'Urgent',
        'demands.overdue': 'Overdue',
        'demands.closed': 'Closed',
        'demands.queue': 'Work queue',
        'demands.onTable': 'What is on the table',
        'demands.filterByStatus': 'Filter by status',
        'demands.allStatus': 'All status',
        'demands.filterByPriority': 'Filter by priority',
        'demands.allPriorities': 'All priorities',
        'demands.refresh': 'Refresh tasks',
        'demands.loading': 'Refreshing queue...',
        'demands.emptyTitle': 'Queue clear.',
        'demands.emptyDescription': 'Add the next task to get work moving.',
        'demands.noDeadline': 'No deadline set',
        'demands.notFinalized': 'Not finalized',
        'demands.edit': 'Edit task',
        'demands.delete': 'Delete task',
        'demands.viewDetails': 'View task details',
        'demands.detailsKicker': 'Task details',
        'demands.createdAt': 'Created at',
        'demands.page': 'Page',
        'demands.of': 'of',
        'demands.previousPage': 'Previous page',
        'demands.nextPage': 'Next page',
        'demands.editKicker': 'Course correction',
        'demands.newKicker': 'Quick entry',
        'demands.new': 'New task',
        'demands.editDescription': 'Update the record as the work moves forward.',
        'demands.newDescription': 'Capture now. Refine while executing.',
        'demands.title': 'Title',
        'demands.titlePlaceholder': 'E.g.: Review customer endpoint',
        'demands.description': 'Description',
        'demands.descriptionPlaceholder': 'Describe what needs to be done',
        'demands.reviewNote': 'Review note',
        'demands.optional': 'optional',
        'demands.reviewNotePlaceholder': 'Record context, decisions or the expected result for review',
        'demands.deadline': 'Deadline',
        'demands.finalizedAt': 'Finalized at',
        'demands.status': 'Status',
        'demands.priority': 'Priority',
        'demands.save': 'Save changes',
        'demands.cancelEdit': 'Cancel editing',
        'demands.footerTagline': 'Your daily delivery log.',
        'demands.footerText': 'Organize the present. Document progress.',
        'demands.backToTop': 'Back to top',
        'demands.deleteKicker': 'Permanent action',
        'demands.deleteTitle': 'Remove task',
        'demands.close': 'Close',
        'demands.deleteQuestion': 'Remove this item from the queue?',
        'demands.deleteDescriptionStart': 'The task',
        'demands.deleteDescriptionEnd': 'will be permanently removed. This action cannot be undone.',
        'demands.keep': 'Keep task',
        'demands.deleting': 'Removing...',
        'demands.remove': 'Remove task',
        'demands.loadError': 'Could not load your tasks.',
        'demands.searchError': 'Could not search your tasks.',
        'demands.registerError': 'Could not add the task.',
        'demands.editError': 'Could not edit the task.',
        'demands.deleteError': 'Could not delete the task.',
        'status.PENDING': 'Pending',
        'status.ONGOING': 'Ongoing',
        'status.BLOCKED': 'Blocked',
        'status.DONE': 'Completed',
        'priority.LOW': 'Low',
        'priority.MEDIUM': 'Medium',
        'priority.HIGH': 'High',
        'priority.URGENT': 'Urgent',
    },
    es: {
        'language.label': 'Idioma',
        'language.pt-BR': 'Portugués - BR',
        'language.en': 'Inglés',
        'language.es': 'Español',
        'theme.light': 'Activar modo claro',
        'theme.dark': 'Activar modo oscuro',
        'auth.bannerAlt': 'Workhub, un hub completo para organizar, colaborar y entregar más.',
        'auth.email': 'Email',
        'auth.emailPlaceholder': 'tu@empresa.com',
        'auth.password': 'Contraseña',
        'auth.passwordPlaceholder': 'Tu contraseña',
        'auth.login.eyebrow': 'Login',
        'auth.login.title': 'Accede a tu cuenta',
        'auth.login.description': 'Inicia sesión para seguir tus tareas, proyectos y entregas.',
        'auth.login.submit': 'Entrar',
        'auth.login.noAccount': '¿Aún no tienes una cuenta?',
        'auth.login.createAccount': 'Crear cuenta',
        'auth.register.eyebrow': 'Registro',
        'auth.register.title': 'Crea tu cuenta',
        'auth.register.description': 'Después del registro, iniciarás sesión en Workhub.',
        'auth.register.firstName': 'Nombre',
        'auth.register.firstNamePlaceholder': 'Tu nombre',
        'auth.register.lastName': 'Apellido',
        'auth.register.lastNamePlaceholder': 'Tu apellido',
        'auth.register.username': 'Username',
        'auth.register.passwordPlaceholder': 'Mínimo de 8 caracteres',
        'auth.register.submit': 'Crear cuenta',
        'auth.register.hasAccount': '¿Ya tienes una cuenta?',
        'auth.register.signIn': 'Entrar',
        'validation.email': 'Ingresa un email válido.',
        'validation.passwordRequired': 'Ingresa tu contraseña.',
        'validation.passwordMin': 'La contraseña debe tener al menos 8 caracteres.',
        'validation.usernameMin': 'El username debe tener al menos 2 caracteres.',
        'validation.usernameMax': 'El username debe tener como máximo 30 caracteres.',
        'validation.lastNameMin': 'El apellido debe tener al menos 2 caracteres.',
        'validation.lastNameMax': 'El apellido debe tener como máximo 30 caracteres.',
        'validation.firstNameMin': 'El nombre debe tener al menos 2 caracteres.',
        'validation.firstNameMax': 'El nombre debe tener como máximo 20 caracteres.',
        'toast.success': 'Operación completada',
        'toast.error': 'No se pudo completar',
        'auth.register.success': '¡Usuario registrado con éxito!',
        'auth.register.error': 'Ocurrió un error durante el registro. ¡Inténtalo de nuevo más tarde!',
        'auth.login.success': '¡Inicio de sesión exitoso!',
        'auth.login.error': 'Email o contraseña inválidos.',
        'demands.nav': 'Tareas',
        'demands.mainNav': 'Navegación principal',
        'demands.user': 'Usuario',
        'demands.search': 'Buscar tareas',
        'demands.searchPlaceholder': 'Buscar por título',
        'demands.clearSearch': 'Limpiar búsqueda',
        'demands.logout': 'Salir',
        'demands.personalPanel': 'Panel personal',
        'demands.heading': 'Tareas en',
        'demands.headingEmphasis': 'movimiento.',
        'demands.intro': 'Una visión directa del trabajo que debe avanzar.',
        'demands.register': 'Registrar tarea',
        'demands.currentSlice': 'Recorte actual',
        'demands.items': 'Ítems',
        'demands.ongoing': 'En curso',
        'demands.urgent': 'Urgentes',
        'demands.overdue': 'Atrasadas',
        'demands.closed': 'Cerradas',
        'demands.queue': 'Cola de trabajo',
        'demands.onTable': 'Lo que está sobre la mesa',
        'demands.filterByStatus': 'Filtrar por status',
        'demands.allStatus': 'Todos los status',
        'demands.filterByPriority': 'Filtrar por prioridad',
        'demands.allPriorities': 'Todas las prioridades',
        'demands.refresh': 'Actualizar tareas',
        'demands.loading': 'Actualizando la cola...',
        'demands.emptyTitle': 'Cola libre.',
        'demands.emptyDescription': 'Registra la próxima tarea para poner el trabajo en movimiento.',
        'demands.noDeadline': 'Sin plazo definido',
        'demands.notFinalized': 'No finalizada',
        'demands.edit': 'Editar tarea',
        'demands.delete': 'Eliminar tarea',
        'demands.viewDetails': 'Ver detalles de la tarea',
        'demands.detailsKicker': 'Detalles de la tarea',
        'demands.createdAt': 'Creada el',
        'demands.page': 'Página',
        'demands.of': 'de',
        'demands.previousPage': 'Página anterior',
        'demands.nextPage': 'Página siguiente',
        'demands.editKicker': 'Ajuste de ruta',
        'demands.newKicker': 'Entrada rápida',
        'demands.new': 'Nueva tarea',
        'demands.editDescription': 'Actualiza el registro a medida que avanza el trabajo.',
        'demands.newDescription': 'Captura ahora. Refina mientras ejecutas.',
        'demands.title': 'Título',
        'demands.titlePlaceholder': 'Ej.: Revisar endpoint de clientes',
        'demands.description': 'Descripción',
        'demands.descriptionPlaceholder': 'Describe lo que debe realizarse',
        'demands.reviewNote': 'Nota para review',
        'demands.optional': 'opcional',
        'demands.reviewNotePlaceholder': 'Registra contexto, decisiones o el resultado esperado para consultar en el review',
        'demands.deadline': 'Plazo',
        'demands.finalizedAt': 'Finalizada el',
        'demands.status': 'Status',
        'demands.priority': 'Prioridad',
        'demands.save': 'Guardar cambios',
        'demands.cancelEdit': 'Cancelar edición',
        'demands.footerTagline': 'Tu registro diario de entregas.',
        'demands.footerText': 'Organiza el presente. Documenta lo que avanzó.',
        'demands.backToTop': 'Volver arriba',
        'demands.deleteKicker': 'Acción permanente',
        'demands.deleteTitle': 'Eliminar tarea',
        'demands.close': 'Cerrar',
        'demands.deleteQuestion': '¿Retirar este ítem de la cola?',
        'demands.deleteDescriptionStart': 'La tarea',
        'demands.deleteDescriptionEnd': 'será eliminada permanentemente. Esta acción no se puede deshacer.',
        'demands.keep': 'Mantener tarea',
        'demands.deleting': 'Eliminando...',
        'demands.remove': 'Eliminar tarea',
        'demands.loadError': 'No se pudieron cargar tus tareas.',
        'demands.searchError': 'No se pudieron buscar tus tareas.',
        'demands.registerError': 'No se pudo registrar la tarea.',
        'demands.editError': 'No se pudo editar la tarea.',
        'demands.deleteError': 'No se pudo eliminar la tarea.',
        'status.PENDING': 'Pendiente',
        'status.ONGOING': 'En curso',
        'status.BLOCKED': 'Bloqueada',
        'status.DONE': 'Completada',
        'priority.LOW': 'Baja',
        'priority.MEDIUM': 'Media',
        'priority.HIGH': 'Alta',
        'priority.URGENT': 'Urgente',
    },
} as const;

export type TranslationKey = keyof typeof messages['pt-BR'];

const language = ref<Language>('pt-BR');

const getPreferredLanguage = (): Language => {
    const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);

    if (storedLanguage === 'pt-BR' || storedLanguage === 'en' || storedLanguage === 'es')
        return storedLanguage;

    if (navigator.language.toLowerCase().startsWith('es'))
        return 'es';

    return navigator.language.toLowerCase().startsWith('en') ? 'en' : 'pt-BR';
};

const applyLanguage = (value: Language) => {
    language.value = value;
    document.documentElement.lang = value;
};

export const initializeLanguage = () => applyLanguage(getPreferredLanguage());

export const translate = (key: TranslationKey) => messages[language.value][key];

export const useLanguage = () => {
    const setLanguage = (value: Language) => {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, value);
        applyLanguage(value);
    };

    return {
        language,
        setLanguage,
        t: translate,
    };
};
